<div class = "alert alert-block alert-info">
    <h1> Module 2 - Data Manipulation </h1>
    <h2> Data Cleaning </h2>
   </div>

In [2]:
# Import the required libraries

import pandas as pd
import numpy as np

In [42]:
df_csv = pd.read_csv('Superstore-Small.csv', encoding='latin-1')
df_csv

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298.0,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.6500,7.0,0.00,762.1845,933.57,Critical
1,26341.0,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.3950,9.0,0.10,-288.7650,923.63,Critical
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25330.0,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.1710,9.0,0.10,919.9710,915.49,Medium
4,13524.0,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.5100,5.0,0.10,-96.5400,910.16,Medium
5,47221.0,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.9600,8.0,0.00,311.5200,903.04,Critical
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22732.0,IN-2013-42360,28-06-2013,01-07-2013,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,...,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.6750,5.0,0.10,763.2750,897.35,Critical
8,30570.0,IN-2011-81826,07-11-2011,09-11-2011,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.0800,4.0,0.00,564.8400,894.77,Critical
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,31192.0,IN-2012-86369,14-04-2012,18-04-2012,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.8400,6.0,0.00,996.4800,878.38,High
11,40155.0,CA-2014-135909,14-10-2014,21-10-2014,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.9600,5.0,0.20,1906.4850,867.69,Low
12,40936.0,CA-2012-116638,28-01-2012,31-01-2012,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.6440,13.0,0.40,-1862.3124,865.74,Critical
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,34577.0,CA-2011-102988,05-04-2011,09-04-2011,Second Class,GM-14695,Greg Maxwell,Corporate,Alexandria,Virginia,...,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,4164.0500,5.0,0.00,83.2810,846.54,High
15,28879.0,ID-2012-28402,19-04-2012,22-04-2012,First Class,AJ-10780,Anthony Jacobs,Corporate,Kabul,Kabul,...,FUR-TA-10001889,Furniture,Tables,"Bevis Conference Table, Fully Assembled",4626.1500,5.0,0.00,647.5500,835.57,High
16,45794.0,SA-2011-1830,27-12-2011,29-12-2011,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,...,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.9600,4.0,0.00,1151.4000,832.41,Critical
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,4132.0,MX-2012-130015,13-11-2012,13-11-2012,Same Day,VF-21715,Vicky Freymann,Home Office,Toledo,Parana,...,FUR-CH-10002033,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",2221.8000,7.0,0.00,622.0200,810.25,Critical
19,27704.0,IN-2013-73951,06-06-2013,08-06-2013,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,...,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.5200,12.0,0.00,1036.0800,804.54,Critical
20,13779.0,ES-2014-5099955,31-07-2014,03-08-2014,Second Class,BP-11185,Ben Peterman,Corporate,Paris,Ile-de-France,...,OFF-AP-10000423,Office Supplies,Appliances,"Breville Refrigerator, Red",1869.5880,4.0,0.10,186.9480,801.66,Critical
21,36178.0,CA-2014-143567,03-11-2014,06-11-2014,Second Class,TB-21175,Thomas Boland,Corporate,Henderson,Kentucky,...,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,2249.9100,9.0,0.00,517.4793,780.70,Critical
22,12069.0,ES-2014-1651774,08-09-2014,14-09-2014,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",7958.5800,14.0,0.00,3979.0800,778.32,Low
23,22096.0,IN-2014-11763,31-01-2014,01-02-2014,First Class,JS-15685,Jim Sink,Corporate,Townsville,Queensland,...,TEC-CO-10000865,Technology,Copiers,"Brother Fax Machine, High-Speed",2565.5940,9.0,0.10,28.4040,766.93,Critical
24,49463.0,TZ-2014-8190,05-12-2014,07-12-2014,Second Class,RH-9555,Ritsa Hightower,Consumer,Uvinza,Kigoma,...,OFF-KIT-10004058,Office Supplies,Appliances,"KitchenAid Stove, White",3409.7400,6.0,0.00,818.2800,763.38,High
25,46630.0,PL-2012-7820,08-08-2012,10-08-2012,First Class,AB-600,Ann Blume,Corporate,Bytom,Silesia,...,FUR-HON-10000224,Furniture,Tables,"Hon Computer Table, with Bottom Storage",1977.7200,4.0,0.00,276.8400,759.47,Critical
26,31784.0,CA-2011-154627,29-10-2011,31-10-2011,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,...,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,2735.9520,6.0,0.20,341.9940,752.51,High
27,21586.0,IN-2011-44803,02-05-2011,03-05-2011,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,...,FUR-CH-10000027,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",2754.0000,6.0,0.00,358.0200,752.47,Critical
28,13528.0,ES-2013-2860574,27-02-2013,01-03-2013,Second Class,LB-16795,Laurel Beltran,Home Office,Edinburgh,Scotland,...,OFF-AP-10003590,Office Supplies,Appliances,"KitchenAid Refrigerator, Black",5273.7000,10.0,0.00,1898.4000,730.91,High
29,1570.0,US-2014-133193,31-07-2014,01-08-2014,First Class,NP-18325,Naresj Patel,Consumer,Juárez,Chihuahua,...,TEC-PH-10004182,Technology,Phones,"Motorola Smart Phone, Full Size",1713.8400,4.0,0.00,445.5200,728.97,Critical
30,3484.0,MX-2014-165309,05-09-2014,08-09-2014,First Class,VD-21670,Valerie Dominguez,Consumer,Soyapango,San Salvador,...,FUR-TA-10002827,Furniture,Tables,"Hon Computer Table, Fully Assembled",2106.4960,8.0,0.20,526.4960,728.39,Critical
31,30191.0,IN-2011-10286,17-12-2011,20-12-2011,First Class,PB-19210,Phillip Breyer,Corporate,Taipei,Taipei City,...,FUR-TA-10004744,Furniture,Tables,"Lesro Conference Table, with Bottom Storage",1715.1600,2.0,0.00,720.3600,725.57,Critical
32,11645.0,ES-2011-4699764,14-03-2011,17-03-2011,Second Class,EB-14110,Eugene Barchas,Consumer,Leipzig,Saxony,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",3069.7380,6.0,0.10,1364.2380,725.34,Critical
33,37311.0,CA-2013-159016,11-03-2013,12-03-2013,First Class,KF-16285,Karen Ferguson,Home Office,Los Angeles,California,...,TEC-PH-10002885,Technology,Phones,Apple iPhone 5,4158.9120,8.0,0.20,363.9048,714.66,High
34,22999.0,IN-2012-44810,25-02-2012,25-02-2012,Same Day,BP-11230,Benjamin Patterson,Consumer,Surat,Gujarat,...,FUR-CH-10001415,Furniture,Chairs,"Office Star Executive Leather Armchair, Red",1878.7200,4.0,0.00,582.3600,704.08,Critical
35,220.0,US-2011-128776,28-12-2011,30-12-2011,Second Class,RR-19525,Rick Reed,Corporate,Santo Domingo,Santo Domingo,...,TEC-PH-10002815,Technology,Phones,"Samsung Smart Phone, VoIP",1696.6400,5.0,0.20,-148.4600,704.06,Critical
36,10648.0,ES-2012-5870268,17-07-2012,19-07-2012,First Class,BS-11365,Bill Shonely,Corporate,Saint-Brieuc,Brittany,...,TEC-MA-10000161,Technology,Machines,"Okidata Inkjet, Wireless",2402.8650,9.0,0.15,763.1550,699.55,Critical
37,32735.0,CA-2012-139731,15-10-2012,15-10-2012,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,...,FUR-CH-10002024,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,2453.4300,5.0,0.30,-350.4900,690.42,High
38,21286.0,IN-2011-28087,03-11-2011,05-11-2011,Second Class,DP-13105,Dave Poirier,Corporate,Gold Coast,Queensland,...,OFF-AP-10004246,Office Supplies,Appliances,"Breville Stove, Red",2526.9300,5.0,0.10,561.4800,689.80,Critical
39,32543.0,CA-2011-168494,12-12-2011,14-12-2011,Second Class,NP-18700,Nora Preis,Consumer,Fresno,California,...,FUR-TA-10003473,Furniture,Tables,Bretford Rectangular Conference Table Tops,3610.8480,12.0,0.20,135.4068,683.12,High
40,47905.0,CG-2011-8610,14-09-2011,15-09-2011,First Class,AH-30,Aaron Hawkins,Corporate,Kamina,Katanga,...,TEC-APP-10000308,Technology,Phones,"Apple Smart Phone, Full Size",3817.2600,6.0,0.00,1068.6600,678.15,High
41,36423.0,CA-2011-160766,14-09-2011,14-09-2011,Same Day,DM-13015,Darrin Martin,Consumer,New York City,New York,...,TEC-MA-10003979,Technology,Machines,Ativa V4110MDD Micro-Cut Shredder,2799.9600,4.0,0.00,1371.9804,675.15,High
42,31980.0,US-2014-168116,05-11-2014,05-11-2014,Same Day,GT-14635,Grant Thornton,Corporate,Burlington,North Carolina,...,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.9800,4.0,0.50,-3839.9904,674.82,High
43,15380.0,ES-2014-2637201,14-01-2014,18-01-2014,Standard Class,PO-18865,Patrick O'Donnell,Consumer,Stockton-on-Tees,England,...,TEC-CO-10000013,Technology,Copiers,"Brother Fax Machine, Laser",4141.0200,13.0,0.00,1697.6700,668.96,High
44,28046.0,IN-2011-61302,10-01-2011,11-01-2011,First Class,DL-12865,Dan Lawera,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",2875.0950,5.0,0.10,511.0950,665.27,Medium
45,21316.0,ID-2013-63976,22-08-2013,26-08-2013,Standard Class,JB-16000,Joy Bell-,Consumer,Mataram,Nusa Tenggara Barat,...,TEC-PH-10000499,Technology,Phones,"Motorola Smart Phone, Full Size",3200.5962,6.0,0.17,-77.2038,660.87,High
46,29272.0,IN-2014-37320,11-11-2014,15-11-2014,Standard Class,BF-11005,Barry Franz,Home Office,Gorakhpur,Haryana,...,TEC-PH-10003856,Technology,Phones,"Motorola Smart Phone, with Caller ID",4518.7800,7.0,0.00,632.5200,658.69,High
47,25795.0,IN-2014-76016,26-09-2014,28-09-2014,Second Class,VG-21805,Vivek Grady,Corporate,Thiruvananthapuram,Kerala,...,FUR-BO-10004852,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.8700,13.0,0.00,2097.0300,658.35,Medium
48,16681.0,ES-2012-5877219,13-12-2012,17-12-2012,Standard Class,GT-14710,Greg Tran,Consumer,Huddersfield,England,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",5785.0200,9.0,0.00,404.7300,656.73,High
49,31784.0,CA-2011-154627,29-10-2011,31-10-2011,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,...,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,2735.9520,6.0,0.20,341.9940,752.51,High
50,21586.0,IN-2011-44803,02-05-2011,03-05-2011,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,...,FUR-CH-10000027,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",2754.0000,6.0,0.00,358.0200,752.47,Critical

### Understand the dataset

In [1]:
df_csv.shape

NameError: name 'df_csv' is not defined

In [43]:
print(f"The number of rows in dataset is {df_csv.shape[0]}")
print(f"The number of columns in dataset is {df_csv.shape[1]}")

The number of rows in dataset is 51
The number of columns in dataset is 25

In [15]:
#Display the first few rows of dataset
df_csv.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298.0,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7.0,0.0,762.1845,933.57,Critical
1,26341.0,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9.0,0.1,-288.7650,923.63,Critical
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,25330.0,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9.0,0.1,919.9710,915.49,Medium
4,13524.0,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5.0,0.1,-96.5400,910.16,Medium
5,47221.0,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8.0,0.0,311.5200,903.04,Critical
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,22732.0,IN-2013-42360,28-06-2013,01-07-2013,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,...,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.675,5.0,0.1,763.2750,897.35,Critical
8,30570.0,IN-2011-81826,07-11-2011,09-11-2011,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.080,4.0,0.0,564.8400,894.77,Critical
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#Display the last 5 rows of dataset
df_csv.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
46,29272.0,IN-2014-37320,11-11-2014,15-11-2014,Standard Class,BF-11005,Barry Franz,Home Office,Gorakhpur,Haryana,...,TEC-PH-10003856,Technology,Phones,"Motorola Smart Phone, with Caller ID",4518.780,7.0,0.0,632.520,658.69,High
47,25795.0,IN-2014-76016,26-09-2014,28-09-2014,Second Class,VG-21805,Vivek Grady,Corporate,Thiruvananthapuram,Kerala,...,FUR-BO-10004852,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.870,13.0,0.0,2097.030,658.35,Medium
48,16681.0,ES-2012-5877219,13-12-2012,17-12-2012,Standard Class,GT-14710,Greg Tran,Consumer,Huddersfield,England,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",5785.020,9.0,0.0,404.730,656.73,High
49,31784.0,CA-2011-154627,29-10-2011,31-10-2011,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,...,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,2735.952,6.0,0.2,341.994,752.51,High
50,21586.0,IN-2011-44803,02-05-2011,03-05-2011,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,...,FUR-CH-10000027,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",2754.000,6.0,0.0,358.020,752.47,Critical

In [17]:
# Understand the data type of columns
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          46 non-null     float64
 1   Order ID        46 non-null     object
 2   Order Date      46 non-null     object
 3   Ship Date       46 non-null     object
 4   Ship Mode       46 non-null     object
 5   Customer ID     46 non-null     object
 6   Customer Name   46 non-null     object
 7   Segment         46 non-null     object
 8   City            46 non-null     object
 9   State           46 non-null     object
 10  Blank_col       0 non-null      float64
 11  Country         46 non-null     object
 12  Postal Code     12 non-null     float64
 13  Market          46 non-null     object
 14  Region          46 non-null     object
 15  Product ID      46 non-null     object
 16  Category        46 non-null     object
 17  Sub-Category    46 non-null     object
 18  Product Name    46 non-null     object
 19  Sales           46 non-null     float64
 20  Quantity        46 non-null     float64
 21  Discount        46 non-null     float64
 22  Profit          46 non-null     float64
 23  Shipping Cost   46 non-null     float64
 24  Order Priority  46 non-null     object
dtypes: float64(8), object(17)
memory usage: 10.1+ KB

### Remove blank rows and columns

In [24]:
df_csv.isnull().all().sum()

1

In [21]:
print(f"There are {df_csv.isnull().all(axis=1).sum()} blank rows in the dataset")
print(f"There are {df_csv.isnull().all(axis=0).sum()} blank columns in the dataset")

There are 5 blank rows in the dataset
There are 1 blank columns in the dataset

In [44]:
# Remove blank rows
df_csv.dropna(how='all', axis=0, inplace=True)
df_csv.shape

(46, 25)

In [45]:
# Remove blank columns
df_csv.dropna(how='all', axis=1, inplace=True)
df_csv.shape

(46, 24)

In [31]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          46 non-null     float64
 1   Order ID        46 non-null     object
 2   Order Date      46 non-null     object
 3   Ship Date       46 non-null     object
 4   Ship Mode       46 non-null     object
 5   Customer ID     46 non-null     object
 6   Customer Name   46 non-null     object
 7   Segment         46 non-null     object
 8   City            46 non-null     object
 9   State           46 non-null     object
 10  Country         46 non-null     object
 11  Postal Code     12 non-null     float64
 12  Market          46 non-null     object
 13  Region          46 non-null     object
 14  Product ID      46 non-null     object
 15  Category        46 non-null     object
 16  Sub-Category    46 non-null     object
 17  Product Name    46 non-null     object
 18  Sales           46 non-null     float64
 19  Quantity        46 non-null     float64
 20  Discount        46 non-null     float64
 21  Profit          46 non-null     float64
 22  Shipping Cost   46 non-null     float64
 23  Order Priority  46 non-null     object
dtypes: float64(7), object(17)
memory usage: 9.0+ KB

### Remove unwanted columns

In [46]:
df_csv.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='object')

In [47]:
cols = list(df_csv.columns)
cols

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'City',
 'State',
 'Country',
 'Postal Code',
 'Market',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Cost',
 'Order Priority']

In [40]:
#Example to remove multiple columns 
remove_cols = ['City', 'State', 'Country']
for i in remove_cols:
    cols.pop(cols.index(i))
cols

['Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Postal Code',
 'Market',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales',
 'Quantity',
 'Discount',
 'Profit',
 'Shipping Cost',
 'Order Priority']

In [48]:
cols.pop(cols.index('Row ID'))
df_csv = df_csv[cols]
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        46 non-null     object
 1   Order Date      46 non-null     object
 2   Ship Date       46 non-null     object
 3   Ship Mode       46 non-null     object
 4   Customer ID     46 non-null     object
 5   Customer Name   46 non-null     object
 6   Segment         46 non-null     object
 7   City            46 non-null     object
 8   State           46 non-null     object
 9   Country         46 non-null     object
 10  Postal Code     12 non-null     float64
 11  Market          46 non-null     object
 12  Region          46 non-null     object
 13  Product ID      46 non-null     object
 14  Category        46 non-null     object
 15  Sub-Category    46 non-null     object
 16  Product Name    46 non-null     object
 17  Sales           46 non-null     float64
 18  Quantity        46 non-null     float64
 19  Discount        46 non-null     float64
 20  Profit          46 non-null     float64
 21  Shipping Cost   46 non-null     float64
 22  Order Priority  46 non-null     object
dtypes: float64(6), object(17)
memory usage: 8.6+ KB

In [49]:
df_csv.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'City', 'State', 'Country', 'Postal Code',
       'Market', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Cost', 'Order Priority'],
      dtype='object')

### Identify and Remove Duplicate rows

In [50]:
#Find the duplicated rows in dataset
df_csv.duplicated()

0     False
1     False
3     False
4     False
5     False
7     False
8     False
10    False
11    False
12    False
14    False
15    False
16    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49     True
50     True
dtype: bool

In [53]:
#Find the count of duplicated and unique rows in dataset
df_csv.duplicated().value_counts()

False    44
True      2
dtype: int64

In [55]:
# Check for duplicates based on 2 columns - Order ID and Product ID
df_csv.duplicated(['Order ID','Product ID']).value_counts()

False    44
True      2
dtype: int64

In [62]:
df_csv[['Order ID', 'Product ID', 'Sales']][df_csv.duplicated()]

          Order ID       Product ID     Sales
49  CA-2011-154627  TEC-PH-10001363  2735.952
50   IN-2011-44803  FUR-CH-10000027  2754.000

In [63]:
df_csv[['Order ID', 'Product ID', 'Sales']][df_csv.duplicated(['Order ID', 'Product ID'], keep=False)]

          Order ID       Product ID     Sales
26  CA-2011-154627  TEC-PH-10001363  2735.952
27   IN-2011-44803  FUR-CH-10000027  2754.000
49  CA-2011-154627  TEC-PH-10001363  2735.952
50   IN-2011-44803  FUR-CH-10000027  2754.000

In [64]:
df_csv[['Order ID', 'Product ID', 'Sales']][df_csv.duplicated(['Order ID', 'Product ID'], keep=False)].sort_values(['Order ID', 'Product ID'])

          Order ID       Product ID     Sales
26  CA-2011-154627  TEC-PH-10001363  2735.952
49  CA-2011-154627  TEC-PH-10001363  2735.952
27   IN-2011-44803  FUR-CH-10000027  2754.000
50   IN-2011-44803  FUR-CH-10000027  2754.000

In [65]:
df_csv.drop_duplicates()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.6500,7.0,0.00,762.1845,933.57,Critical
1,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.3950,9.0,0.10,-288.7650,923.63,Critical
3,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.1710,9.0,0.10,919.9710,915.49,Medium
4,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.5100,5.0,0.10,-96.5400,910.16,Medium
5,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.9600,8.0,0.00,311.5200,903.04,Critical
7,IN-2013-42360,28-06-2013,01-07-2013,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,Australia,...,TEC-PH-10000030,Technology,Phones,"Samsung Smart Phone, with Caller ID",2862.6750,5.0,0.10,763.2750,897.35,Critical
8,IN-2011-81826,07-11-2011,09-11-2011,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,New Zealand,...,FUR-CH-10004050,Furniture,Chairs,"Novimex Executive Leather Armchair, Adjustable",1822.0800,4.0,0.00,564.8400,894.77,Critical
10,IN-2012-86369,14-04-2012,18-04-2012,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,New Zealand,...,FUR-TA-10002958,Furniture,Tables,"Chromcraft Conference Table, Fully Assembled",5244.8400,6.0,0.00,996.4800,878.38,High
11,CA-2014-135909,14-10-2014,21-10-2014,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,United States,...,OFF-BI-10003527,Office Supplies,Binders,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.9600,5.0,0.20,1906.4850,867.69,Low
12,CA-2012-116638,28-01-2012,31-01-2012,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,United States,...,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.6440,13.0,0.40,-1862.3124,865.74,Critical
14,CA-2011-102988,05-04-2011,09-04-2011,Second Class,GM-14695,Greg Maxwell,Corporate,Alexandria,Virginia,United States,...,OFF-SU-10002881,Office Supplies,Supplies,Martin Yale Chadless Opener Electric Letter Op...,4164.0500,5.0,0.00,83.2810,846.54,High
15,ID-2012-28402,19-04-2012,22-04-2012,First Class,AJ-10780,Anthony Jacobs,Corporate,Kabul,Kabul,Afghanistan,...,FUR-TA-10001889,Furniture,Tables,"Bevis Conference Table, Fully Assembled",4626.1500,5.0,0.00,647.5500,835.57,High
16,SA-2011-1830,27-12-2011,29-12-2011,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,Saudi Arabia,...,TEC-CIS-10001717,Technology,Phones,"Cisco Smart Phone, with Caller ID",2616.9600,4.0,0.00,1151.4000,832.41,Critical
18,MX-2012-130015,13-11-2012,13-11-2012,Same Day,VF-21715,Vicky Freymann,Home Office,Toledo,Parana,Brazil,...,FUR-CH-10002033,Furniture,Chairs,"Harbour Creations Executive Leather Armchair, ...",2221.8000,7.0,0.00,622.0200,810.25,Critical
19,IN-2013-73951,06-06-2013,08-06-2013,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,China,...,OFF-AP-10003500,Office Supplies,Appliances,"KitchenAid Microwave, White",3701.5200,12.0,0.00,1036.0800,804.54,Critical
20,ES-2014-5099955,31-07-2014,03-08-2014,Second Class,BP-11185,Ben Peterman,Corporate,Paris,Ile-de-France,France,...,OFF-AP-10000423,Office Supplies,Appliances,"Breville Refrigerator, Red",1869.5880,4.0,0.10,186.9480,801.66,Critical
21,CA-2014-143567,03-11-2014,06-11-2014,Second Class,TB-21175,Thomas Boland,Corporate,Henderson,Kentucky,United States,...,TEC-AC-10004145,Technology,Accessories,Logitech diNovo Edge Keyboard,2249.9100,9.0,0.00,517.4793,780.70,Critical
22,ES-2014-1651774,08-09-2014,14-09-2014,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,Italy,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",7958.5800,14.0,0.00,3979.0800,778.32,Low
23,IN-2014-11763,31-01-2014,01-02-2014,First Class,JS-15685,Jim Sink,Corporate,Townsville,Queensland,Australia,...,TEC-CO-10000865,Technology,Copiers,"Brother Fax Machine, High-Speed",2565.5940,9.0,0.10,28.4040,766.93,Critical
24,TZ-2014-8190,05-12-2014,07-12-2014,Second Class,RH-9555,Ritsa Hightower,Consumer,Uvinza,Kigoma,Tanzania,...,OFF-KIT-10004058,Office Supplies,Appliances,"KitchenAid Stove, White",3409.7400,6.0,0.00,818.2800,763.38,High
25,PL-2012-7820,08-08-2012,10-08-2012,First Class,AB-600,Ann Blume,Corporate,Bytom,Silesia,Poland,...,FUR-HON-10000224,Furniture,Tables,"Hon Computer Table, with Bottom Storage",1977.7200,4.0,0.00,276.8400,759.47,Critical
26,CA-2011-154627,29-10-2011,31-10-2011,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,United States,...,TEC-PH-10001363,Technology,Phones,Apple iPhone 5S,2735.9520,6.0,0.20,341.9940,752.51,High
27,IN-2011-44803,02-05-2011,03-05-2011,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,China,...,FUR-CH-10000027,Furniture,Chairs,"SAFCO Executive Leather Armchair, Black",2754.0000,6.0,0.00,358.0200,752.47,Critical
28,ES-2013-2860574,27-02-2013,01-03-2013,Second Class,LB-16795,Laurel Beltran,Home Office,Edinburgh,Scotland,United Kingdom,...,OFF-AP-10003590,Office Supplies,Appliances,"KitchenAid Refrigerator, Black",5273.7000,10.0,0.00,1898.4000,730.91,High
29,US-2014-133193,31-07-2014,01-08-2014,First Class,NP-18325,Naresj Patel,Consumer,Juárez,Chihuahua,Mexico,...,TEC-PH-10004182,Technology,Phones,"Motorola Smart Phone, Full Size",1713.8400,4.0,0.00,445.5200,728.97,Critical
30,MX-2014-165309,05-09-2014,08-09-2014,First Class,VD-21670,Valerie Dominguez,Consumer,Soyapango,San Salvador,El Salvador,...,FUR-TA-10002827,Furniture,Tables,"Hon Computer Table, Fully Assembled",2106.4960,8.0,0.20,526.4960,728.39,Critical
31,IN-2011-10286,17-12-2011,20-12-2011,First Class,PB-19210,Phillip Breyer,Corporate,Taipei,Taipei City,Taiwan,...,FUR-TA-10004744,Furniture,Tables,"Lesro Conference Table, with Bottom Storage",1715.1600,2.0,0.00,720.3600,725.57,Critical
32,ES-2011-4699764,14-03-2011,17-03-2011,Second Class,EB-14110,Eugene Barchas,Consumer,Leipzig,Saxony,Germany,...,OFF-AP-10004512,Office Supplies,Appliances,"Hoover Stove, Red",3069.7380,6.0,0.10,1364.2380,725.34,Critical
33,CA-2013-159016,11-03-2013,12-03-2013,First Class,KF-16285,Karen Ferguson,Home Office,Los Angeles,California,United States,...,TEC-PH-10002885,Technology,Phones,Apple iPhone 5,4158.9120,8.0,0.20,363.9048,714.66,High
34,IN-2012-44810,25-02-2012,25-02-2012,Same Day,BP-11230,Benjamin Patterson,Consumer,Surat,Gujarat,India,...,FUR-CH-10001415,Furniture,Chairs,"Office Star Executive Leather Armchair, Red",1878.7200,4.0,0.00,582.3600,704.08,Critical
35,US-2011-128776,28-12-2011,30-12-2011,Second Class,RR-19525,Rick Reed,Corporate,Santo Domingo,Santo Domingo,Dominican Republic,...,TEC-PH-10002815,Technology,Phones,"Samsung Smart Phone, VoIP",1696.6400,5.0,0.20,-148.4600,704.06,Critical
36,ES-2012-5870268,17-07-2012,19-07-2012,First Class,BS-11365,Bill Shonely,Corporate,Saint-Brieuc,Brittany,France,...,TEC-MA-10000161,Technology,Machines,"Okidata Inkjet, Wireless",2402.8650,9.0,0.15,763.1550,699.55,Critical
37,CA-2012-139731,15-10-2012,15-10-2012,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,United States,...,FUR-CH-10002024,Furniture,Chairs,HON 5400 Series Task Chairs for Big and Tall,2453.4300,5.0,0.30,-350.4900,690.42,High
38,IN-2011-28087,03-11-2011,05-11-2011,Second Class,DP-13105,Dave Poirier,Corporate,Gold Coast,Queensland,Australia,...,OFF-AP-10004246,Office Supplies,Appliances,"Breville Stove, Red",2526.9300,5.0,0.10,561.4800,689.80,Critical
39,CA-2011-168494,12-12-2011,14-12-2011,Second Class,NP-18700,Nora Preis,Consumer,Fresno,California,United States,...,FUR-TA-10003473,Furniture,Tables,Bretford Rectangular Conference Table Tops,3610.8480,12.0,0.20,135.4068,683.12,High
40,CG-2011-8610,14-09-2011,15-09-2011,First Class,AH-30,Aaron Hawkins,Corporate,Kamina,Katanga,Democratic Republic of the Congo,...,TEC-APP-10000308,Technology,Phones,"Apple Smart Phone, Full Size",3817.2600,6.0,0.00,1068.6600,678.15,High
41,CA-2011-160766,14-09-2011,14-09-2011,Same Day,DM-13015,Darrin Martin,Consumer,New York City,New York,United States,...,TEC-MA-10003979,Technology,Machines,Ativa V4110MDD Micro-Cut Shredder,2799.9600,4.0,0.00,1371.9804,675.15,High
42,US-2014-168116,05-11-2014,05-11-2014,Same Day,GT-14635,Grant Thornton,Corporate,Burlington,North Carolina,United States,...,TEC-MA-10004125,Technology,Machines,Cubify CubeX 3D Printer Triple Head Print,7999.9800,4.0,0.50,-3839.9904,674.82,High
43,ES-2014-2637201,14-01-2014,18-01-2014,Standard Class,PO-18865,Patrick O'Donnell,Consumer,Stockton-on-Tees,England,United Kingdom,...,TEC-CO-10000013,Technology,Copiers,"Brother Fax Machine, Laser",4141.0200,13.0,0.00,1697.6700,668.96,High
44,IN-2011-61302,10-01-2011,11-01-2011,First Class,DL-12865,Dan Lawera,Consumer,Brisbane,Queensland,Australia,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",2875.0950,5.0,0.10,511.0950,665.27,Medium
45,ID-2013-63976,22-08-2013,26-08-2013,Standard Class,JB-16000,Joy Bell-,Consumer,Mataram,Nusa Tenggara Barat,Indonesia,...,TEC-PH-10000499,Technology,Phones,"Motorola Smart Phone, Full Size",3200.5962,6.0,0.17,-77.2038,660.87,High
46,IN-2014-37320,11-11-2014,15-11-2014,Standard Class,BF-11005,Barry Franz,Home Office,Gorakhpur,Haryana,India,...,TEC-PH-10003856,Technology,Phones,"Motorola Smart Phone, with Caller ID",4518.7800,7.0,0.00,632.5200,658.69,High
47,IN-2014-76016,26-09-2014,28-09-2014,Second Class,VG-21805,Vivek Grady,Corporate,Thiruvananthapuram,Kerala,India,...,FUR-BO-10004852,Furniture,Bookcases,"Sauder Classic Bookcase, Traditional",5667.8700,13.0,0.00,2097.0300,658.35,Medium
48,ES-2012-5877219,13-12-2012,17-12-2012,Standard Class,GT-14710,Greg Tran,Consumer,Huddersfield,England,United Kingdom,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",5785.0200,9.0,0.00,404.7300,656.73,High

### Handling Missing Values

In [66]:
df_csv.isna()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
30,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
31,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
32,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
34,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
35,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
36,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
37,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
38,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
39,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
40,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
41,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
42,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
43,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
44,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
45,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
46,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [69]:
df_csv['Postal Code'].isna()

0     False
1      True
3      True
4      True
5      True
7      True
8      True
10     True
11    False
12    False
14    False
15     True
16     True
18     True
19     True
20     True
21    False
22     True
23     True
24     True
25     True
26    False
27     True
28     True
29     True
30     True
31     True
32     True
33    False
34     True
35     True
36     True
37    False
38     True
39    False
40     True
41    False
42    False
43     True
44     True
45     True
46     True
47     True
48     True
49    False
50     True
Name: Postal Code, dtype: bool

In [68]:
df_csv.isna().sum()

Order ID           0
Order Date         0
Ship Date          0
Ship Mode          0
Customer ID        0
Customer Name      0
Segment            0
City               0
State              0
Country            0
Postal Code       34
Market             0
Region             0
Product ID         0
Category           0
Sub-Category       0
Product Name       0
Sales              0
Quantity           0
Discount           0
Profit             0
Shipping Cost      0
Order Priority     0
dtype: int64

In [70]:
df_csv['Postal Code'].fillna(value='No Postal Code', inplace=True)
df_csv.isna().sum()

C:\Users\Bhuvana\AppData\Local\Temp\ipykernel_8840\3108384429.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Postal Code'].fillna(value='No Postal Code', inplace=True)

Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
City              0
State             0
Country           0
Postal Code       0
Market            0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping Cost     0
Order Priority    0
dtype: int64

In [9]:
df_csv['Postal Code'].fillna(value='No Postal Code', inplace=True)
df_csv.isna().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
City              0
State             0
Country           0
Postal Code       0
Market            0
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
Quantity          0
Discount          0
Profit            0
Shipping Cost     0
Order Priority    0
dtype: int64

In [73]:
df_csv['Postal Code']

0            10024.0
1     No Postal Code
3     No Postal Code
4     No Postal Code
5     No Postal Code
7     No Postal Code
8     No Postal Code
10    No Postal Code
11           95823.0
12           28027.0
14           22304.0
15    No Postal Code
16    No Postal Code
18    No Postal Code
19    No Postal Code
20    No Postal Code
21           42420.0
22    No Postal Code
23    No Postal Code
24    No Postal Code
25    No Postal Code
26           60610.0
27    No Postal Code
28    No Postal Code
29    No Postal Code
30    No Postal Code
31    No Postal Code
32    No Postal Code
33           90008.0
34    No Postal Code
35    No Postal Code
36    No Postal Code
37           79109.0
38    No Postal Code
39           93727.0
40    No Postal Code
41           10009.0
42           27217.0
43    No Postal Code
44    No Postal Code
45    No Postal Code
46    No Postal Code
47    No Postal Code
48    No Postal Code
49           60610.0
50    No Postal Code
Name: Postal Code, dtype: object

### Change Data Type of columns

In [77]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        46 non-null     object
 1   Order Date      46 non-null     object
 2   Ship Date       46 non-null     object
 3   Ship Mode       46 non-null     object
 4   Customer ID     46 non-null     object
 5   Customer Name   46 non-null     object
 6   Segment         46 non-null     object
 7   City            46 non-null     object
 8   State           46 non-null     object
 9   Country         46 non-null     object
 10  Postal Code     46 non-null     object
 11  Market          46 non-null     object
 12  Region          46 non-null     object
 13  Product ID      46 non-null     object
 14  Category        46 non-null     object
 15  Sub-Category    46 non-null     object
 16  Product Name    46 non-null     object
 17  Sales           46 non-null     float64
 18  Quantity        46 non-null     float64
 19  Discount        46 non-null     float64
 20  Profit          46 non-null     float64
 21  Shipping Cost   46 non-null     float64
 22  Order Priority  46 non-null     object
dtypes: float64(5), object(18)
memory usage: 8.6+ KB

In [78]:
df_csv.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7.0,0.0,762.1845,933.57,Critical
1,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9.0,0.1,-288.7650,923.63,Critical
3,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9.0,0.1,919.9710,915.49,Medium
4,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5.0,0.1,-96.5400,910.16,Medium
5,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8.0,0.0,311.5200,903.04,Critical

In [79]:
df_csv['Order Date'] = pd.to_datetime(df_csv['Order Date'], dayfirst=True)

C:\Users\Bhuvana\AppData\Local\Temp\ipykernel_8840\1730515053.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Order Date'] = pd.to_datetime(df_csv['Order Date'], dayfirst=True)

In [81]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        46 non-null     object
 1   Order Date      46 non-null     datetime64[ns]
 2   Ship Date       46 non-null     object
 3   Ship Mode       46 non-null     object
 4   Customer ID     46 non-null     object
 5   Customer Name   46 non-null     object
 6   Segment         46 non-null     object
 7   City            46 non-null     object
 8   State           46 non-null     object
 9   Country         46 non-null     object
 10  Postal Code     46 non-null     object
 11  Market          46 non-null     object
 12  Region          46 non-null     object
 13  Product ID      46 non-null     object
 14  Category        46 non-null     object
 15  Sub-Category    46 non-null     object
 16  Product Name    46 non-null     object
 17  Sales           46 non-null     float64
 18  Quantity        46 non-null     float64
 19  Discount        46 non-null     float64
 20  Profit          46 non-null     float64
 21  Shipping Cost   46 non-null     float64
 22  Order Priority  46 non-null     object
dtypes: datetime64[ns](1), float64(5), object(17)
memory usage: 8.6+ KB

In [82]:
df_csv['Ship Date'] = pd.to_datetime(df_csv['Ship Date'], format='%d-%m-%Y')
df_csv.head()

C:\Users\Bhuvana\AppData\Local\Temp\ipykernel_8840\1584358325.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Ship Date'] = pd.to_datetime(df_csv['Ship Date'], format='%d-%m-%Y')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7.0,0.0,762.1845,933.57,Critical
1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9.0,0.1,-288.7650,923.63,Critical
3,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9.0,0.1,919.9710,915.49,Medium
4,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5.0,0.1,-96.5400,910.16,Medium
5,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8.0,0.0,311.5200,903.04,Critical

In [83]:
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        46 non-null     object
 1   Order Date      46 non-null     datetime64[ns]
 2   Ship Date       46 non-null     datetime64[ns]
 3   Ship Mode       46 non-null     object
 4   Customer ID     46 non-null     object
 5   Customer Name   46 non-null     object
 6   Segment         46 non-null     object
 7   City            46 non-null     object
 8   State           46 non-null     object
 9   Country         46 non-null     object
 10  Postal Code     46 non-null     object
 11  Market          46 non-null     object
 12  Region          46 non-null     object
 13  Product ID      46 non-null     object
 14  Category        46 non-null     object
 15  Sub-Category    46 non-null     object
 16  Product Name    46 non-null     object
 17  Sales           46 non-null     float64
 18  Quantity        46 non-null     float64
 19  Discount        46 non-null     float64
 20  Profit          46 non-null     float64
 21  Shipping Cost   46 non-null     float64
 22  Order Priority  46 non-null     object
dtypes: datetime64[ns](2), float64(5), object(16)
memory usage: 8.6+ KB

In [84]:
df_csv['Shipping Cost'] = df_csv['Shipping Cost'].astype('str')
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        46 non-null     object
 1   Order Date      46 non-null     datetime64[ns]
 2   Ship Date       46 non-null     datetime64[ns]
 3   Ship Mode       46 non-null     object
 4   Customer ID     46 non-null     object
 5   Customer Name   46 non-null     object
 6   Segment         46 non-null     object
 7   City            46 non-null     object
 8   State           46 non-null     object
 9   Country         46 non-null     object
 10  Postal Code     46 non-null     object
 11  Market          46 non-null     object
 12  Region          46 non-null     object
 13  Product ID      46 non-null     object
 14  Category        46 non-null     object
 15  Sub-Category    46 non-null     object
 16  Product Name    46 non-null     object
 17  Sales           46 non-null     float64
 18  Quantity        46 non-null     float64
 19  Discount        46 non-null     float64
 20  Profit          46 non-null     float64
 21  Shipping Cost   46 non-null     object
 22  Order Priority  46 non-null     object
dtypes: datetime64[ns](2), float64(4), object(17)
memory usage: 8.6+ KB

C:\Users\Bhuvana\AppData\Local\Temp\ipykernel_8840\1458010588.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Shipping Cost'] = df_csv['Shipping Cost'].astype('str')

In [85]:
df_csv['Shipping Cost'] = df_csv['Shipping Cost'].astype('float')
df_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 46 entries, 0 to 50
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order ID        46 non-null     object
 1   Order Date      46 non-null     datetime64[ns]
 2   Ship Date       46 non-null     datetime64[ns]
 3   Ship Mode       46 non-null     object
 4   Customer ID     46 non-null     object
 5   Customer Name   46 non-null     object
 6   Segment         46 non-null     object
 7   City            46 non-null     object
 8   State           46 non-null     object
 9   Country         46 non-null     object
 10  Postal Code     46 non-null     object
 11  Market          46 non-null     object
 12  Region          46 non-null     object
 13  Product ID      46 non-null     object
 14  Category        46 non-null     object
 15  Sub-Category    46 non-null     object
 16  Product Name    46 non-null     object
 17  Sales           46 non-null     float64
 18  Quantity        46 non-null     float64
 19  Discount        46 non-null     float64
 20  Profit          46 non-null     float64
 21  Shipping Cost   46 non-null     float64
 22  Order Priority  46 non-null     object
dtypes: datetime64[ns](2), float64(5), object(16)
memory usage: 8.6+ KB

C:\Users\Bhuvana\AppData\Local\Temp\ipykernel_8840\1583456310.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_csv['Shipping Cost'] = df_csv['Shipping Cost'].astype('float')

#### Apply formulae - Create new columns or replace values in existing columns

In [86]:
df_csv.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'City', 'State', 'Country', 'Postal Code',
       'Market', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Cost', 'Order Priority'],
      dtype='object')

In [87]:
df_csv['New_column']='abcd'

In [90]:
df_csv['Days Diff'] = df_csv['Ship Date'] - df_csv['Order Date']
df_csv.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,New_column,Days Diff
0,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7.0,0.0,762.1845,933.57,Critical,abcd,0 days
1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9.0,0.1,-288.7650,923.63,Critical,abcd,2 days
3,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9.0,0.1,919.9710,915.49,Medium,abcd,1 days
4,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,Phones,"Motorola Smart Phone, Cordless",2892.510,5.0,0.1,-96.5400,910.16,Medium,abcd,2 days
5,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8.0,0.0,311.5200,903.04,Critical,abcd,1 days

In [91]:
df_csv['Business Days'] = df_csv.apply(lambda x: np.busday_count(x['Order Date'].date(), x['Ship Date'].date()), axis=1)
df_csv.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,New_column,Days Diff,Business Days
0,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7.0,0.0,762.1845,933.57,Critical,abcd,0 days,0
1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,"Novimex Executive Leather Armchair, Black",3709.395,9.0,0.1,-288.7650,923.63,Critical,abcd,2 days,2
3,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,"Nokia Smart Phone, with Caller ID",5175.171,9.0,0.1,919.9710,915.49,Medium,abcd,1 days,1
4,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,"Motorola Smart Phone, Cordless",2892.510,5.0,0.1,-96.5400,910.16,Medium,abcd,2 days,2
5,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,"Sharp Wireless Fax, High-Speed",2832.960,8.0,0.0,311.5200,903.04,Critical,abcd,1 days,1

In [92]:
df_csv

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,New_column,Days Diff,Business Days
0,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,Plantronics CS510 - Over-the-Head monaural Wir...,2309.6500,7.0,0.00,762.1845,933.57,Critical,abcd,0 days,0
1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,"Novimex Executive Leather Armchair, Black",3709.3950,9.0,0.10,-288.7650,923.63,Critical,abcd,2 days,2
3,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,"Nokia Smart Phone, with Caller ID",5175.1710,9.0,0.10,919.9710,915.49,Medium,abcd,1 days,1
4,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,"Motorola Smart Phone, Cordless",2892.5100,5.0,0.10,-96.5400,910.16,Medium,abcd,2 days,2
5,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,"Sharp Wireless Fax, High-Speed",2832.9600,8.0,0.00,311.5200,903.04,Critical,abcd,1 days,1
7,IN-2013-42360,2013-06-28,2013-07-01,Second Class,JM-15655,Jim Mitchum,Corporate,Sydney,New South Wales,Australia,...,"Samsung Smart Phone, with Caller ID",2862.6750,5.0,0.10,763.2750,897.35,Critical,abcd,3 days,1
8,IN-2011-81826,2011-11-07,2011-11-09,First Class,TS-21340,Toby Swindell,Consumer,Porirua,Wellington,New Zealand,...,"Novimex Executive Leather Armchair, Adjustable",1822.0800,4.0,0.00,564.8400,894.77,Critical,abcd,2 days,2
10,IN-2012-86369,2012-04-14,2012-04-18,Standard Class,MB-18085,Mick Brown,Consumer,Hamilton,Waikato,New Zealand,...,"Chromcraft Conference Table, Fully Assembled",5244.8400,6.0,0.00,996.4800,878.38,High,abcd,4 days,2
11,CA-2014-135909,2014-10-14,2014-10-21,Standard Class,JW-15220,Jane Waco,Corporate,Sacramento,California,United States,...,Fellowes PB500 Electric Punch Plastic Comb Bin...,5083.9600,5.0,0.20,1906.4850,867.69,Low,abcd,7 days,5
12,CA-2012-116638,2012-01-28,2012-01-31,Second Class,JH-15985,Joseph Holt,Consumer,Concord,North Carolina,United States,...,Chromcraft Bull-Nose Wood Oval Conference Tabl...,4297.6440,13.0,0.40,-1862.3124,865.74,Critical,abcd,3 days,1
14,CA-2011-102988,2011-04-05,2011-04-09,Second Class,GM-14695,Greg Maxwell,Corporate,Alexandria,Virginia,United States,...,Martin Yale Chadless Opener Electric Letter Op...,4164.0500,5.0,0.00,83.2810,846.54,High,abcd,4 days,4
15,ID-2012-28402,2012-04-19,2012-04-22,First Class,AJ-10780,Anthony Jacobs,Corporate,Kabul,Kabul,Afghanistan,...,"Bevis Conference Table, Fully Assembled",4626.1500,5.0,0.00,647.5500,835.57,High,abcd,3 days,2
16,SA-2011-1830,2011-12-27,2011-12-29,Second Class,MM-7260,Magdelene Morse,Consumer,Jizan,Jizan,Saudi Arabia,...,"Cisco Smart Phone, with Caller ID",2616.9600,4.0,0.00,1151.4000,832.41,Critical,abcd,2 days,2
18,MX-2012-130015,2012-11-13,2012-11-13,Same Day,VF-21715,Vicky Freymann,Home Office,Toledo,Parana,Brazil,...,"Harbour Creations Executive Leather Armchair, ...",2221.8000,7.0,0.00,622.0200,810.25,Critical,abcd,0 days,0
19,IN-2013-73951,2013-06-06,2013-06-08,Second Class,PF-19120,Peter Fuller,Consumer,Mudanjiang,Heilongjiang,China,...,"KitchenAid Microwave, White",3701.5200,12.0,0.00,1036.0800,804.54,Critical,abcd,2 days,2
20,ES-2014-5099955,2014-07-31,2014-08-03,Second Class,BP-11185,Ben Peterman,Corporate,Paris,Ile-de-France,France,...,"Breville Refrigerator, Red",1869.5880,4.0,0.10,186.9480,801.66,Critical,abcd,3 days,2
21,CA-2014-143567,2014-11-03,2014-11-06,Second Class,TB-21175,Thomas Boland,Corporate,Henderson,Kentucky,United States,...,Logitech diNovo Edge Keyboard,2249.9100,9.0,0.00,517.4793,780.70,Critical,abcd,3 days,3
22,ES-2014-1651774,2014-09-08,2014-09-14,Standard Class,PJ-18835,Patrick Jones,Corporate,Prato,Tuscany,Italy,...,"Hoover Stove, Red",7958.5800,14.0,0.00,3979.0800,778.32,Low,abcd,6 days,5
23,IN-2014-11763,2014-01-31,2014-02-01,First Class,JS-15685,Jim Sink,Corporate,Townsville,Queensland,Australia,...,"Brother Fax Machine, High-Speed",2565.5940,9.0,0.10,28.4040,766.93,Critical,abcd,1 days,1
24,TZ-2014-8190,2014-12-05,2014-12-07,Second Class,RH-9555,Ritsa Hightower,Consumer,Uvinza,Kigoma,Tanzania,...,"KitchenAid Stove, White",3409.7400,6.0,0.00,818.2800,763.38,High,abcd,2 days,1
25,PL-2012-7820,2012-08-08,2012-08-10,First Class,AB-600,Ann Blume,Corporate,Bytom,Silesia,Poland,...,"Hon Computer Table, with Bottom Storage",1977.7200,4.0,0.00,276.8400,759.47,Critical,abcd,2 days,2
26,CA-2011-154627,2011-10-29,2011-10-31,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,United States,...,Apple iPhone 5S,2735.9520,6.0,0.20,341.9940,752.51,High,abcd,2 days,0
27,IN-2011-44803,2011-05-02,2011-05-03,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,China,...,"SAFCO Executive Leather Armchair, Black",2754.0000,6.0,0.00,358.0200,752.47,Critical,abcd,1 days,1
28,ES-2013-2860574,2013-02-27,2013-03-01,Second Class,LB-16795,Laurel Beltran,Home Office,Edinburgh,Scotland,United Kingdom,...,"KitchenAid Refrigerator, Black",5273.7000,10.0,0.00,1898.4000,730.91,High,abcd,2 days,2
29,US-2014-133193,2014-07-31,2014-08-01,First Class,NP-18325,Naresj Patel,Consumer,Juárez,Chihuahua,Mexico,...,"Motorola Smart Phone, Full Size",1713.8400,4.0,0.00,445.5200,728.97,Critical,abcd,1 days,1
30,MX-2014-165309,2014-09-05,2014-09-08,First Class,VD-21670,Valerie Dominguez,Consumer,Soyapango,San Salvador,El Salvador,...,"Hon Computer Table, Fully Assembled",2106.4960,8.0,0.20,526.4960,728.39,Critical,abcd,3 days,1
31,IN-2011-10286,2011-12-17,2011-12-20,First Class,PB-19210,Phillip Breyer,Corporate,Taipei,Taipei City,Taiwan,...,"Lesro Conference Table, with Bottom Storage",1715.1600,2.0,0.00,720.3600,725.57,Critical,abcd,3 days,1
32,ES-2011-4699764,2011-03-14,2011-03-17,Second Class,EB-14110,Eugene Barchas,Consumer,Leipzig,Saxony,Germany,...,"Hoover Stove, Red",3069.7380,6.0,0.10,1364.2380,725.34,Critical,abcd,3 days,3
33,CA-2013-159016,2013-03-11,2013-03-12,First Class,KF-16285,Karen Ferguson,Home Office,Los Angeles,California,United States,...,Apple iPhone 5,4158.9120,8.0,0.20,363.9048,714.66,High,abcd,1 days,1
34,IN-2012-44810,2012-02-25,2012-02-25,Same Day,BP-11230,Benjamin Patterson,Consumer,Surat,Gujarat,India,...,"Office Star Executive Leather Armchair, Red",1878.7200,4.0,0.00,582.3600,704.08,Critical,abcd,0 days,0
35,US-2011-128776,2011-12-28,2011-12-30,Second Class,RR-19525,Rick Reed,Corporate,Santo Domingo,Santo Domingo,Dominican Republic,...,"Samsung Smart Phone, VoIP",1696.6400,5.0,0.20,-148.4600,704.06,Critical,abcd,2 days,2
36,ES-2012-5870268,2012-07-17,2012-07-19,First Class,BS-11365,Bill Shonely,Corporate,Saint-Brieuc,Brittany,France,...,"Okidata Inkjet, Wireless",2402.8650,9.0,0.15,763.1550,699.55,Critical,abcd,2 days,2
37,CA-2012-139731,2012-10-15,2012-10-15,Same Day,JE-15745,Joel Eaton,Consumer,Amarillo,Texas,United States,...,HON 5400 Series Task Chairs for Big and Tall,2453.4300,5.0,0.30,-350.4900,690.42,High,abcd,0 days,0
38,IN-2011-28087,2011-11-03,2011-11-05,Second Class,DP-13105,Dave Poirier,Corporate,Gold Coast,Queensland,Australia,...,"Breville Stove, Red",2526.9300,5.0,0.10,561.4800,689.80,Critical,abcd,2 days,2
39,CA-2011-168494,2011-12-12,2011-12-14,Second Class,NP-18700,Nora Preis,Consumer,Fresno,California,United States,...,Bretford Rectangular Conference Table Tops,3610.8480,12.0,0.20,135.4068,683.12,High,abcd,2 days,2
40,CG-2011-8610,2011-09-14,2011-09-15,First Class,AH-30,Aaron Hawkins,Corporate,Kamina,Katanga,Democratic Republic of the Congo,...,"Apple Smart Phone, Full Size",3817.2600,6.0,0.00,1068.6600,678.15,High,abcd,1 days,1
41,CA-2011-160766,2011-09-14,2011-09-14,Same Day,DM-13015,Darrin Martin,Consumer,New York City,New York,United States,...,Ativa V4110MDD Micro-Cut Shredder,2799.9600,4.0,0.00,1371.9804,675.15,High,abcd,0 days,0
42,US-2014-168116,2014-11-05,2014-11-05,Same Day,GT-14635,Grant Thornton,Corporate,Burlington,North Carolina,United States,...,Cubify CubeX 3D Printer Triple Head Print,7999.9800,4.0,0.50,-3839.9904,674.82,High,abcd,0 days,0
43,ES-2014-2637201,2014-01-14,2014-01-18,Standard Class,PO-18865,Patrick O'Donnell,Consumer,Stockton-on-Tees,England,United Kingdom,...,"Brother Fax Machine, Laser",4141.0200,13.0,0.00,1697.6700,668.96,High,abcd,4 days,4
44,IN-2011-61302,2011-01-10,2011-01-11,First Class,DL-12865,Dan Lawera,Consumer,Brisbane,Queensland,Australia,...,"Nokia Smart Phone, with Caller ID",2875.0950,5.0,0.10,511.0950,665.27,Medium,abcd,1 days,1
45,ID-2013-63976,2013-08-22,2013-08-26,Standard Class,JB-16000,Joy Bell-,Consumer,Mataram,Nusa Tenggara Barat,Indonesia,...,"Motorola Smart Phone, Full Size",3200.5962,6.0,0.17,-77.2038,660.87,High,abcd,4 days,2
46,IN-2014-37320,2014-11-11,2014-11-15,Standard Class,BF-11005,Barry Franz,Home Office,Gorakhpur,Haryana,India,...,"Motorola Smart Phone, with Caller ID",4518.7800,7.0,0.00,632.5200,658.69,High,abcd,4 days,4
47,IN-2014-76016,2014-09-26,2014-09-28,Second Class,VG-21805,Vivek Grady,Corporate,Thiruvananthapuram,Kerala,India,...,"Sauder Classic Bookcase, Traditional",5667.8700,13.0,0.00,2097.0300,658.35,Medium,abcd,2 days,1
48,ES-2012-5877219,2012-12-13,2012-12-17,Standard Class,GT-14710,Greg Tran,Consumer,Huddersfield,England,United Kingdom,...,"Motorola Smart Phone, Cordless",5785.0200,9.0,0.00,404.7300,656.73,High,abcd,4 days,2
49,CA-2011-154627,2011-10-29,2011-10-31,First Class,SA-20830,Sue Ann Reed,Consumer,Chicago,Illinois,United States,...,Apple iPhone 5S,2735.9520,6.0,0.20,341.9940,752.51,High,abcd,2 days,0
50,IN-2011-44803,2011-05-02,2011-05-03,First Class,JK-15325,Jason Klamczynski,Corporate,Suzhou,Anhui,China,...,"SAFCO Executive Leather Armchair, Black",2754.0000,6.0,0.00,358.0200,752.47,Critical,abcd,1 days,1

In [94]:
df_csv['Order Year'] = df_csv['Order Date'].dt.year
df_csv['Order Month'] = df_csv['Order Date'].dt.month
df_csv.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,...,Quantity,Discount,Profit,Shipping Cost,Order Priority,New_column,Days Diff,Business Days,Order Year,Order Month
0,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,United States,...,7.0,0.0,762.1845,933.57,Critical,abcd,0 days,0,2012,7
1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,Australia,...,9.0,0.1,-288.7650,923.63,Critical,abcd,2 days,2,2013,2
3,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,Australia,...,9.0,0.1,919.9710,915.49,Medium,abcd,1 days,1,2013,10
4,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,Germany,...,5.0,0.1,-96.5400,910.16,Medium,abcd,2 days,2,2013,1
5,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,Senegal,...,8.0,0.0,311.5200,903.04,Critical,abcd,1 days,1,2013,11